import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const currentDirectory = path.dirname(currentFile);
const projectRoot = path.resolve(currentDirectory, "..");

const seedGuideDirectory = path.join(
  projectRoot,
  "public",
  "guides",
  "seeds"
);

const outputDirectory = path.join(
  projectRoot,
  "src",
  "data",
  "plants"
);

const outputFile = path.join(
  outputDirectory,
  "generatedSeedGuideIndex.js"
);

function titleCase(value) {
  const lowercaseWords = new Set([
    "and",
    "of",
    "the",
    "de",
  ]);

  return value
    .split("-")
    .filter(Boolean)
    .map((word, index) => {
      if (index > 0 && lowercaseWords.has(word)) {
        return word;
      }

      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(" ");
}

function cleanGuideSlug(filename) {
  return filename
    .replace(/\.pdf$/i, "")
    .replace(/-grow-instructions$/i, "")
    .replace(/-plant-grow-instructions$/i, "")
    .replace(/^organic-/i, "")
    .replace(/-plant$/i, "")
    .replace(/-{2,}/g, "-")
    .replace(/^-|-$/g, "");
}

function detectCategory(slug) {
  const categoryRules = [
    {
      category: "Beans",
      keywords: ["bean", "beans"],
    },
    {
      category: "Corn",
      keywords: ["corn"],
    },
    {
      category: "Cucumbers",
      keywords: ["cucumber", "cucumbers"],
    },
    {
      category: "Peppers",
      keywords: [
        "pepper",
        "jalapeno",
        "habanero",
        "bell",
      ],
    },
    {
      category: "Tomatoes",
      keywords: ["tomato", "tomatoes"],
    },
    {
      category: "Herbs",
      keywords: [
        "chamomile",
        "oregano",
        "lavender",
        "peppermint",
        "sage",
        "cilantro",
        "basil",
        "parsley",
        "thyme",
        "rosemary",
      ],
    },
    {
      category: "Leafy Greens",
      keywords: [
        "broccoli",
        "kale",
        "mizuna",
        "spinach",
        "romaine",
        "lettuce",
        "chard",
      ],
    },
    {
      category: "Root Vegetables",
      keywords: [
        "beet",
        "radish",
        "carrot",
        "turnip",
      ],
    },
    {
      category: "Peas",
      keywords: ["pea", "peas"],
    },
    {
      category: "Melons",
      keywords: [
        "watermelon",
        "melon",
        "cantaloupe",
      ],
    },
    {
      category: "Vegetables",
      keywords: ["celery"],
    },
  ];

  const matchingRule = categoryRules.find((rule) =>
    rule.keywords.some((keyword) => slug.includes(keyword))
  );

  return matchingRule?.category ?? "Vegetables";
}

function createGuideEntry(filename) {
  const slug = cleanGuideSlug(filename);
  const commonName = titleCase(slug);

  return {
    id: slug,
    slug,
    commonName,
    category: detectCategory(slug),
    pdfPath: `/guides/seeds/${filename}`,
  };
}

if (!fs.existsSync(seedGuideDirectory)) {
  console.error(
    `Seed guide folder not found:\n${seedGuideDirectory}`
  );

  process.exit(1);
}

const filenames = fs
  .readdirSync(seedGuideDirectory)
  .filter((filename) => filename.toLowerCase().endsWith(".pdf"))
  .sort((a, b) => a.localeCompare(b));

const guideEntries = filenames.map(createGuideEntry);

fs.mkdirSync(outputDirectory, {
  recursive: true,
});

const output = `/*
 * AUTO-GENERATED FILE
 *
 * Generated by:
 * npm run generate:seeds
 *
 * Do not add custom plant information here.
 * Add corrections and details to seedPlantOverrides.js instead.
 */

export const generatedSeedGuideIndex = ${JSON.stringify(
  guideEntries,
  null,
  2
)};
`;

fs.writeFileSync(outputFile, output, "utf8");

console.log(
  `Generated ${guideEntries.length} seed-guide entries.`
);

console.log(`Saved to:\n${outputFile}`);